import os

PROJECT_DIRS = [
    "src",
    "src/agents",
    "src/config",
    "src/graph",
    "src/modules",
    "src/tools",
    "src/utils",
    "tests",
    "tests/unit",
    "tests/integration",
]

PROJECT_FILES = [
    ".env",
    "pyproject.toml",
    "README.md",

    "src/__init__.py",
    "src/main.py",

    "src/agents/__init__.py",
    "src/agents/supervisor.py",
    "src/agents/researcher.py",
    "src/agents/analyst.py",
    "src/agents/evaluator.py",
    "src/agents/utils.py",

    "src/config/__init__.py",
    "src/config/settings.py",

    "src/graph/__init__.py",
    "src/graph/state.py",
    "src/graph/workflow.py",
    "src/graph/checkpoints.py",

    "src/modules/__init__.py",
    "src/modules/responses.py",

    "src/tools/__init__.py",
    "src/tools/base.py",
    "src/tools/data_tools.py",
    "src/tools/registry.py",
    "src/tools/search_tools.py",

    "src/utils/__init__.py",
    "src/utils/groq_client.py",
    "src/utils/logger.py",
    "src/utils/memory.py",
    "src/utils/tracing.py",

    "tests/__init__.py",
    "tests/unit/__init__.py",
    "tests/integration/__init__.py",
]


def ensure_parent_dir(path: str) -> None:
    parent = os.path.dirname(path)
    if parent and not os.path.exists(parent):
        os.makedirs(parent, exist_ok=True)


def create_directories(dirs):
    for directory in dirs:
        os.makedirs(directory, exist_ok=True)
        print(f"Ensured directory: {directory}")


def create_files(files):
    for file in files:
        ensure_parent_dir(file)
        if not os.path.exists(file):
            with open(file, "w", encoding="utf-8") as f:
                f.write(f"# Auto-generated by setup_project.py — {file}\n")
            print(f"Created file: {file}")
        else:
            print(f"Skipped (exists): {file}")


if __name__ == "__main__":
    create_directories(PROJECT_DIRS)
    create_files(PROJECT_FILES)
    print("\nProject structure setup complete.")